-- GeoRoster KYC document vault metadata migration.
-- Additive only; document bytes remain outside the database.

CREATE TABLE IF NOT EXISTS employee_kyc_documents (
    document_id INT AUTO_INCREMENT PRIMARY KEY,
    kyc_id INT NOT NULL,
    employee_id INT NOT NULL,
    amendment_id INT DEFAULT NULL,
    document_type VARCHAR(40) NOT NULL,
    document_label VARCHAR(120) DEFAULT NULL,
    version_no INT NOT NULL,
    is_current TINYINT(1) NOT NULL DEFAULT 0,
    lifecycle_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    original_filename_enc VARCHAR(768) NOT NULL,
    validated_mime VARCHAR(100) NOT NULL,
    file_extension VARCHAR(10) NOT NULL,
    plaintext_size INT UNSIGNED NOT NULL,
    encrypted_size INT UNSIGNED NOT NULL,
    content_hmac CHAR(64) NOT NULL,
    storage_key VARCHAR(180) NOT NULL,
    encryption_scheme VARCHAR(30) NOT NULL,
    uploaded_by INT NOT NULL,
    uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    superseded_by INT DEFAULT NULL,
    superseded_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active_document_slot TINYINT GENERATED ALWAYS AS (CASE WHEN is_current = 1 AND lifecycle_status = 'ACTIVE' THEN 1 ELSE NULL END) STORED,
    UNIQUE KEY uq_kyc_document_storage_key (storage_key),
    UNIQUE KEY uq_kyc_document_version (employee_id, document_type, version_no),
    UNIQUE KEY uq_kyc_document_current (employee_id, document_type, active_document_slot),
    KEY idx_kyc_documents_kyc (kyc_id),
    KEY idx_kyc_documents_employee (employee_id),
    KEY idx_kyc_documents_amendment (amendment_id),
    KEY idx_kyc_documents_status (lifecycle_status, is_current),
    CONSTRAINT chk_kyc_document_type CHECK (document_type IN ('PAN_CARD', 'AADHAAR_CARD', 'UAN_PROOF', 'ESIC_CARD', 'ADDRESS_PROOF', 'EMPLOYEE_PHOTO', 'OTHER_KYC')),
    CONSTRAINT chk_kyc_document_status CHECK (lifecycle_status IN ('ACTIVE', 'PENDING_AMENDMENT', 'SUPERSEDED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT fk_kyc_document_kyc FOREIGN KEY (kyc_id) REFERENCES employee_kyc(kyc_id) ON DELETE CASCADE,
    CONSTRAINT fk_kyc_document_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE RESTRICT,
    CONSTRAINT fk_kyc_document_amendment FOREIGN KEY (amendment_id) REFERENCES employee_kyc_amendments(amendment_id) ON DELETE SET NULL,
    CONSTRAINT fk_kyc_document_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_kyc_document_superseded_by FOREIGN KEY (superseded_by) REFERENCES employee_kyc_documents(document_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
